### ISSUE TITLE
localFile.url is not local for svg and gif files

### ISSUE THREAD

**Issue by samirfors** [angeloashmore/gatsby-source-prismic#232] opened 2020-05-27 10:38 UTC
Hello, 

It seems gifs and svgs are not being downloaded, even though `shouldDownloadImage: () => true` in `gatsby-config.js`

This is part of my query
```
items {
  image {
    alt
    localFile {
      url
      childImageSharp {
        fluid(maxWidth: 550) {
          ...GatsbyImageSharpFluid
        }
      }
    }
  }
}
```

For any file that is *not* a gif or svg the files are loaded with childImageSharp and url points to `/static/...` but for gifs and svgs the image source points to `https://images.prismic.io/...`

The query above can be seen with one gif and one png file here: https://staging--quizrr-site.netlify.app/non-local-gifs/ 

Is this intended behaviour?

**Comment by angeloashmore** [comment] 2020-06-05 03:53
Hi @samirfors, sorry for the delayed response.

`gatsby-transformer-sharp` and `gatsby-plugin-sharp` do not support GIFs and SVGs as inputs. Using `localFile.childImageSharp` is powered by those two plugins.

See this issue: https://github.com/gatsbyjs/gatsby/issues/7317

If you need to have fluid GIFs and SVGs, I would recommend using `fluid` using the Imgix URLs instead. Prismic provides this functionality by default.

See this part of the docs: https://github.com/angeloashmore/gatsby-source-prismic#using-imgix-transformed-images

**Comment by angeloashmore** [comment] 2020-06-05 03:54
Closing this for now as it is intended behavior, but please post here if you're running into issues. Thanks!

**Closed by angeloashmore** 2020-06-05 03:53 UTC

**Comment by samirfors** [comment] 2020-06-05 09:30
Thank you for your response @angeloashmore. 

Sorry, I was being a bit unclear. I'm actually more interested in the `localFile.url`-part. I understand that `childImageSharp` isn't populated here, but I thought `localFile.url` would point to a downloaded version of the gif/svg when `shouldDownloadImage` is set to true? 

In the below example, both `image.url` and `image.localFile.url` point to the remote image on Prismic.

```
image {
  url
  localFile {
    url
  }
}
```

**Comment by angeloashmore** [comment] 2020-06-05 19:34
@samirfors I see, sorry for misunderstanding.

The following URL fields are sometimes available on File nodes, depending on the setup:

 - `localFile.url`: points to the source image URL, which in this case is the Imgix/Prismic URL.
- `localFile.publicURL`: points to the local URL that can be used in your site. This **does not** work for plugins using `gatsby-source-filesystem` programmatically, like this one.

If you use `gatsby-source-filesystem` by itself, for example to load a folder of assets, then it will add the extra `publicURL` field to `File`. If `gatsby-source-filesystem` is not in your `gatsby-config.js`, however, then `publicURL` is never added.

**Solutions** - Either of the following should work

1. Setup `gatsby-source-filesystem` and point it to any file, such as `gatsby-config.js`:
   ```js
   {
     resolve: 'gatsby-source-filesystem',
     options: {
       path: `${__dirname}/gatsby-config.js`,
     },
   }
   ```

   `publicURL` should now be available on all `localFile` fields.

1. Install [`gatsby-transformer-remote-filesystem`](https://github.com/mjmaurer/gatsby-transformer-remote-filesystem) (community plugin)

   `localURL` should now be available on all `localFile` fields.

**Comment by angeloashmore** [comment] 2020-06-05 19:34
These issues detail why and how this happens:

https://github.com/gatsbyjs/gatsby/issues/18001
https://github.com/gatsbyjs/gatsby/issues/19935

**Comment by samirfors** [comment] 2020-06-06 10:41
@angeloashmore Great answer, thank you for clarifying! 

Adding `gatsby-source-filesystem` to `gatsby-config.js` did the trick indeed.
