### ISSUE TITLE
v3 - dataRaw shape is inferred, not JSON

### ISSUE THREAD

**Issue by angeloashmore** [angeloashmore/gatsby-source-prismic#112] opened 2019-06-25 00:11 UTC
`dataRaw` should be `JSON` type, but Gatsby seems to infer the object. It shouldn't.

**Comment by asyarb** [comment] 2019-07-09 19:29
Couldn't reproduce issue in test sites. Closing for now.

**Closed by asyarb** 2019-07-09 19:29 UTC
