### ISSUE TITLE
Support for Gatsby 3

### ISSUE THREAD

**Issue by iqbal125** [angeloashmore/gatsby-source-prismic#332] opened 2021-04-08 02:09 UTC
Hello is this meant to work with Gatsby 3? Im running into errors while trying to install with Gatsby 3.

**Comment by angeloashmore** [comment] 2021-04-08 02:20
Yes, this plugin is used in Gatsby 3 projects. Could you share the error you are encountering?

**Comment by iqbal125** [comment] 2021-04-08 18:57
I could be wrong but it seems its failing becuase its saying this module needs v2 of gatsby-source-filesystem which itself needs Gatsby v2. 

![image](https://user-images.githubusercontent.com/24860061/114081536-86750e00-9861-11eb-8824-9b49410b1bc9.png)


my package.json

{
  "name": "saas-starter-kit",
  "description": "Saas Starterkit Blog",
  "dependencies": {
    "babel-plugin-styled-components": "^1.12.0",
    "dotenv": "^8.2.0",
    "gatsby": "^3.2.1",
    "gatsby-plugin-algolia": "^0.18.0",
    "gatsby-plugin-google-gtag": "^3.2.0",
    "gatsby-plugin-image": "^1.2.0",
    "gatsby-plugin-react-helmet": "^4.2.0",
    "gatsby-plugin-sharp": "^3.2.0",
    "gatsby-plugin-styled-components": "^4.2.0",
    "gatsby-source-prismic": "^3.3.4",
    "gatsby-transformer-sharp": "^3.2.0",
    "moment": "^2.29.1",
    "prismic-reactjs": "^1.3.3",
    "prismjs": "^1.23.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-headroom": "^3.1.0",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.2.0",
    "react-instantsearch": "^6.10.3",
    "react-instantsearch-dom": "^6.10.3",
    "react-syntax-highlighter": "^15.4.3",
    "styled-components": "^5.2.1",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
    "babel-jest": "^26.6.3",
    "babel-preset-gatsby": "^1.1.0",
    "cypress": "^6.7.1",
    "jest": "^26.6.3",
    "prettier": "2.2.1"
  },
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  }
}

**Comment by iqbal125** [comment] 2021-04-08 18:58
It works when I remove only this module and install all the others. I then just install this one with --force

**Comment by angeloashmore** [comment] 2021-04-08 19:52
Thanks, I'l take a look. I'm using Yarn in my projects using Gatsby 3 which may not have the same dependency resolution issue. I'll likely publish a new version that upgrades `gatsby-source-filesystem`.

**Comment by iqbal125** [comment] 2021-04-08 20:03
@angeloashmore awesome! also thanks for making this library!

**Comment by angeloashmore** [comment] 2021-04-10 21:32
@iqbal125 I'm taking a look at this now. I just started a new Gatsby v3 project using the default starter and added `gatsby-source-prismic`.

There is a warning about gatsby-source-filesystem asking for a Gatsby v2 as a peer dependency, but I am still able to develop and build the site without issues. I tested the site with and without gatsby-source-filesystem as a dependency to the site.

```
npm WARN gatsby-source-filesystem@2.11.1 requires a peer of gatsby@^2.2.0 but none is installed. You must install peer dependencies yourself.
```

Could you share your Node and NPM versions? I wonder if the error you're encountering is due to an older package resolution algorithm.

For reference, this is what I tested on:
**Node version**: v14.16.0
**NPM version**: 6.14.11

**Comment by iqbal125** [comment] 2021-04-10 22:51
Im using npm 7 maybe thats the problem. I tried installing on the Gatsby Default starter and am running into the same error. 

![image](https://user-images.githubusercontent.com/24860061/114286470-dbf11c80-9a13-11eb-9a27-31719ad3f432.png)

![image](https://user-images.githubusercontent.com/24860061/114286547-92ed9800-9a14-11eb-91f5-72d0c960f46e.png)

**Comment by angeloashmore** [comment] 2021-04-10 23:35
Ah, thanks for that info. I haven't used NPM for several years now so I didn't realize 7 was the latest.

I was able to reproduce the issue you're seeing. I published a pre-release version that upgrade gatsby-source-filesystem.

```
npm install -S gatsby-source-prismic@gatsby-v3-compat
```

Could you try that out and let me know if you're able to install and use the plugin? If it works, then I'll publish it as a new version.

Normally source plugins should upgrade the peer dependency on Gatsby to v3 and publish a major version (i.e. 4.0.0 for this plugin), but we are close to publishing the next major version with many new features as v4.0.0. As such, I'm going to treat the Gatsby v3 fix for this version of the plugin as a bug fix and will keep the peer dependency at Gatsby v2. There will be a warning from NPM, but it can be ignored (provided everything is still working as expected).

**Comment by LekoArts** [comment] 2021-04-13 08:24
You probably also get around this issue when you use the `--legacy-peer-deps` flag, see: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#updating-community-plugins

**Comment by angeloashmore** [comment] 2021-04-22 20:22
This should be resolved as of `v3.3.5`. Please let me know if you still run into issues and I can take a look.

Thanks!

**Closed by angeloashmore** 2021-04-22 20:22 UTC

**Comment by michaeljblum** [comment] 2021-05-26 01:32
Not to reopen this issue @angeloashmore, but - quick question - would I have to upgrade to V3 or V4 of GSP in order to make use of Gatsby v3 (and gatsby-plugin-image etc.), or are these compatible with even V2 of GSP? Thanks!

**Comment by angeloashmore** [comment] 2021-05-26 01:36
Hey @michaeljblum, you can use Gatsby V3 on `gatsby-source-prismic` V3. If you use npm, you will most likely need to use the `--legacy-peer-deps` in order to install the plugin due to peer dependency version mismatches.

`gatsby-source-prismic` V3 does not have a support for `gatsby-plugin-image` using Imgix, but you can use it with an image's `localFile` field and `gatsby-transformer-sharp`.

V4 will have a native `gatsbyImageData` field for Imgix URLs, if you use it.

I'll be publishing a beta for V4 very soon. If you already have an existing project or a time-sensitive deadline, I would stick with V3 for now. If you have some flexibility or are just trying things out, the V4 beta may be a good fit once it's published.

**Comment by michaeljblum** [comment] 2021-05-26 04:06
Thanks so much for the swift reply @angeloashmore. I'll go ahead and upgrade to GSP v3 when I next have enough free time so I can bump up to v3 of Gatsby, thanks.

**Comment by angeloashmore** [comment] 2021-05-26 04:08
Awesome! Good luck, and feel free to open an issue here or post on the Prismic forum if you have questions.
