### ISSUE TITLE
<PreviewStoreProvider> doesn't seem to get rendered

### ISSUE THREAD

**Issue by davidli3100** [angeloashmore/gatsby-source-prismic#248] opened 2020-07-07 14:01 UTC
Referencing #246 

@angeloashmore I'm not sure if the PR you made somehow screwed up unpublished previews in another way, but the unpublished previews that were working for me a week ago just suddenly stopped.

When I go into React devtools, it actually shows that the `<PreviewStoreProvider>` isn't wrapping anything at all - in fact, it's not even there - which is quite strange. But then published pages are able to be previewed without any issues. Any idea why this might be happening?

**Comment by angeloashmore** [comment] 2020-07-07 19:20
Hi @davidli3100, the PR hasn't been merged or published so no changes have been made to the plugin since `v3.1.4`.

Can you confirm that `<PreviewStoreProvider>` is wrapping your entire app using `wrapRootElement`? Details are available here: https://github.com/angeloashmore/gatsby-source-prismic/blob/master/docs/previews.md#previewstoreprovider

**Comment by davidli3100** [comment] 2020-07-10 04:04
Yeah it’s wrapping the app in Gatsby Node and Gatsby Browser

**Comment by fredshevek** [comment] 2020-08-09 15:41
Hi @davidli3100 

Did you find the root cause, or any solutions to the problem? I seem to have the exact same problem.

**Comment by angeloashmore** [comment] 2020-08-15 21:08
Hi @davidli3100, sorry for such a late response. I'm not sure how to reproduce this. Are you able to make a simple version of your site and share that here? Or is your website source available publicly?

@fredshevek Likewise, if you can provide a reproduction I can take a look at it.

Thanks!

**Comment by davidli3100** [comment] 2020-08-15 21:11
Hi Angelo,

Honestly, I'm not sure what's going on either. It seemed to fix itself
after a couple days and previews run fine now?
Not sure if @fredshevek is still having the same issues.

**Comment by angeloashmore** [comment] 2020-08-15 21:22
Glad to hear it's working okay now. 👍 There were some changes introduced in `v3.2.0` that may have fixed/affected this, but hard to tell.

I'll keep this issue open in case @fredshevek is still experiencing it.

**Comment by fredshevek** [comment] 2020-08-16 08:50
Hey @angeloashmore, I believe this was due to the confusion I mentioned in #256.
All good now, you can close the issue. Thanks

**Comment by angeloashmore** [comment] 2020-08-16 10:12
Awesome, thanks!

**Closed by angeloashmore** 2020-08-16 10:12 UTC
